menu:
  主页: / || fas fa-home
  时间轴: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  关于: /about/ || fas fa-heart

avatar:
  img: /img/xiaogong.jpg
  effect: false

index_img: /img/fengmian.png

subtitle:
  enable: true
  effect: true
  source: 3
  sub: []

enter_transitions: true

darkmode:
  enable: true
  button: true
  autoChangeMode: 1

translate:
  enable: false

aside:
  enable: true
  hide: false
  button: true
  mobile: true
  position: left
  card_author:
    enable: true
    description: ''
    button:
      enable: false
  card_announcement:
    enable: true
    content: 欢迎来到『annnan』的小站(￣▽￣)～■干杯□～(￣▽￣)
  card_recent_post:
    enable: true
    limit: 5
  card_archives:
    enable: true
    type: monthly
    format: MMMM YYYY
    order: -1
    limit: 8
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true

footer:
  owner:
    enable: true
    since: 2021
  custom_text: Hi, welcome to my blog!

background: "#49b1f5"

preloader:
  enable: true
  source: 1

readmode: true
rightside_scroll_percent: true

inject:
  bottom:
    - <script type="text/javascript" src="https://unpkg.zhimg.com/jquery@latest/dist/jquery.min.js"></script>
    - <script defer src="https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js"></script>
    - <script data-pjax defer src="https://npm.elemecdn.com/tzy-blog/lib/js/theme/chocolate.js"></script>

clickShowText:
  enable: true
  text:
    - 富强
    - 民主
    - 文明
    - 和谐
    - 爱国
    - 敬业
    - 诚信
    - 友善
    - 公正
    - 法制
  fontSize: 15px
  random: false
  mobile: false

busuanzi:
  site_uv: false
  site_pv: false
  page_pv: false
